### PR TITLE
Bump version to 1.2

### PR DESCRIPTION
**Pull request by kylestach**

### CODE REVIEW

**Comment by Arvind-Srinivasan** [comment]
Should we wait till we have ADC before we merge this, or do we want to bump with ADC to 1.3?

**Comment by kylestach** [comment]
I've already pushed to bintray, ADC can be 1.3.

**Comment by Arvind-Srinivasan** [comment]
@kylestach has this been pushed to bintray, then it should be merged?

**Comment by kylestach** [comment]
Yes, please review so I can merge.

**Pull request merged**
